### ISSUE TITLE
 jquery-c2.4.3.profile not working

### ISSUE THREAD

**Issue by DarknightCanada** [threatexpress/malleable-c2#11]
Trying to load the profile : ./teamserver ip password jquery-c2.4.3.profile and keep getting this error! all other profiles work fine

`*] Will use existing X509 certificate and keystore (for SSL)
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[-] Error(s) while compiling jquery-c2.4.3.profile
Error: invalid option for <Global> at line 71
       data_jitter
Error: Block is not valid for <Global> at line 190
       dns-beacon
Error: invalid option for <Global> at line 222
       ssh_pipename
Error: invalid option for <.post-ex> at line 322
       pipename
Error: invalid option for <.post-ex> at line 323
       keylogger
Error: invalid option for <.stage> at line 361
       allocator
Error: invalid option for <.stage> at line 364
       magic_pe
Error: invalid option for <.http-config> at line 512
       block_useragents
[-] exiting because of errors in jquery-c2.4.3.profile. Use ./c2lint to check the file
`

**Comment by andrewchiles** [comment]
What version of Cobalt Strike are you using?
Have you made any changes to the file? 
What does the output of `./c2lint jquery-c2.4.3.profile` give you?

**Comment by DarknightCanada** [comment]
4.1 and I have not made any changes! and when I run ./c2lint I get this error:

`/c2lint jquery-c2.4.3.profile
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[-] Error(s) while compiling jquery-c2.4.3.profile
Error: invalid option for <Global> at line 71
       data_jitter
Error: Block is not valid for <Global> at line 190
       dns-beacon
Error: invalid option for <Global> at line 222
       ssh_pipename
Error: invalid option for <.post-ex> at line 322
       pipename
Error: invalid option for <.post-ex> at line 323
       keylogger
Error: invalid option for <.stage> at line 361
       allocator
Error: invalid option for <.stage> at line 364
       magic_pe
Error: invalid option for <.http-config> at line 512
       block_useragents
`

**Comment by andrewchiles** [comment]
The `jquery-c2.4.3.profile` is only compatible with CS 4.3+. If you're using CS 4.1 then you'll need to upgrade.
