### ISSUE TITLE
set compile_time BUG

### ISSUE THREAD

**Issue by butnomingzi** [threatexpress/malleable-c2#6]
[-] Error(s) while compiling ./malleable-c2/jquery-c2.4.2.profile
Error: option <.stage.compile_time> requires a 'dd MMM YYYY hh:mm:ss' date at line 352
       "11 Nov 2016 04:08:32"

。。。

**Comment by andrewchiles** [comment]
Hi, I just verified that`./malleable-c2/jquery-c2.4.2.profile`  passes the latest version of c2lint with Cobalt Strike 4.2 without issues. I verified the timestamp you provided and didn't have any issues. Make sure you're using the latest version of Cobalt Strike.

**Comment by Labster22** [comment]
You can comment out that line
#set compile_time   "11 Nov 2016 04:08:32";

**Comment by Labster22** [comment]
You can comment out that line
#set compile_time   "11 Nov 2016 04:08:32";
